#ifndef GUARD_CONFIG_MODULE_IDS_H
#define GUARD_CONFIG_MODULE_IDS_H

// Project-owned stable IDs. The generic module manager does not assign these;
// an integration build extends this list when it adds another module.
enum ModuleId
{
    MODULE_ID_RANDOMIZER,
    MODULE_ID_NUZLOCKE,
    MODULE_ID_CHEATS,
    MODULE_ID_QOL,
    MODULE_ID_BATTLE_PACING,
    MODULE_ID_PROGRESSION,
    MODULE_ID_POKEMON_RULES,
    MODULE_ID_START_MENU_UI,
    MODULE_ID_DIFFICULTY,
    MODULE_ID_OVERWORLD_FEATURES,
    MODULE_ID_GAME_MODES,
    MODULE_ID_ACTIVE_BATTLE,
    MODULE_ID_KEY_ITEM_DOCK,
    MODULE_ID_SHARED_TRANSFER_BOX,
    MODULE_ID_BENCH_ATTACKER_DAMAGE,
    MODULE_ID_MODERN_SHOP_UI,
    MODULE_ID_GAME_CORNER,
    MODULE_ID_COUNT,
};

#endif // GUARD_CONFIG_MODULE_IDS_H
