#ifndef GUARD_EXTENDED_OPTIONS_H
#define GUARD_EXTENDED_OPTIONS_H

#include "global.h"

enum ExtendedOption
{
    EXT_OPT_AUTO_RUN,
    EXT_OPT_RUNNING_INDOORS,
    EXT_OPT_ITEM_DESCRIPTIONS,
    EXT_OPT_REPEL_PROMPT,
    EXT_OPT_BATTLE_SPEED,
    EXT_OPT_FAST_BATTLE_INTRO,
    EXT_OPT_FAST_HP_BARS,
    EXT_OPT_FAST_EXP_BARS,
    EXT_OPT_MOVE_INFO,
    EXT_OPT_EFFECTIVENESS_HINTS,
    EXT_OPT_OPPONENT_INFO,
    EXT_OPT_BENCH_ATTACKER,
    EXT_OPT_REUSABLE_TMS,
    EXT_OPT_EXP_ON_CATCH,
    EXT_OPT_PARTY_EXP_SHARE,
    EXT_OPT_FIELD_POISON,
    EXT_OPT_TRAINER_ESCAPE,
    EXT_OPT_DIFFICULTY,
    EXT_OPT_ENCOUNTER_STYLE,
    EXT_OPT_FOLLOWER,
    EXT_OPT_SHINY_ODDS,
    EXT_OPT_LEVEL_CAPS,
    EXT_OPT_NUZLOCKE,
    EXT_OPT_RANDOM_TRAINERS,
    EXT_OPT_RANDOM_GIFTS_STATIC,
    EXT_OPT_RANDOM_ALL_DATA,
    EXT_OPT_COUNT,
};

enum
{
    ITEM_DESCRIPTIONS_OFF,
    ITEM_DESCRIPTIONS_FIRST,
    ITEM_DESCRIPTIONS_ALWAYS,
};

enum
{
    BATTLE_SPEED_NORMAL,
    BATTLE_SPEED_FAST,
    BATTLE_SPEED_INSTANT,
};

enum
{
    ENCOUNTER_STYLE_VISIBLE,
    ENCOUNTER_STYLE_TRADITIONAL,
};

enum
{
    SHINY_ODDS_8192,
    SHINY_ODDS_4096,
    SHINY_ODDS_2048,
    SHINY_ODDS_1024,
    SHINY_ODDS_512,
    SHINY_ODDS_256,
    SHINY_ODDS_128,
    SHINY_ODDS_64,
    SHINY_ODDS_ALWAYS,
};
enum
{
    LEVEL_CAPS_OFF,
    LEVEL_CAPS_NORMAL,
    LEVEL_CAPS_HARD,
};

void ExtendedOptions_Init(void);
u8 ExtendedOptions_Get(enum ExtendedOption option);
void ExtendedOptions_Set(enum ExtendedOption option, u8 value);
u8 ExtendedOptions_GetMax(enum ExtendedOption option);

#endif // GUARD_EXTENDED_OPTIONS_H
